### ISSUE TITLE
Integration of wallet app

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/aeweb-cli#20]
### Problem to solve

With flutter, I have coded and generated the web version (only one code = IOS/Android/Web)
the source code of the app is here: [https://github.com/archethic-foundation/archethic_mobile_wallet](https://github.com/archethic-foundation/archethic_mobile_wallet)
the build is here: [https://github.com/redDwarf03/archethic_web](https://github.com/redDwarf03/archethic_web)
NB: I can't create the build on ArchEthic-foundation/archethic_mobile_wallet because I can't access to the settings of the project...

The web app is available here: [https://reddwarf03.github.io/archethic_web/](https://reddwarf03.github.io/archethic_web/)

I would like to host on testnet the web app but I don't understand to host a structure of files (not only one page).

Could you help me

### Solution

add instructions to publish a web app with folders

**Comment by samuel-uniris** [comment]
Hi @redDwarf03 
This feature is planned and under development right now, we will update it soon.
Thanks for the sharing.
