### ISSUE TITLE
Refactor deploy website and folder to avoid DRY

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/aeweb-cli#39]
### Problem to solve

A lot of code is duplicated and can be shared like:
- file directory listing
- funds seeding for file based transaction
- sending of transaction
...

Using lib, utils or modules should be good to avoid this duplication and reduce the readability complexity

### Solution 

DRY (Don't repeat yourself) is a software development principle, the main aim of which is to reduce repetition of code.
The main advantages of DRY are - 

1. Maintainability
2. Readability
3. Reusability
4. Testing

In the current codebase, the following two files have a lot of duplication of code - 

1. https://github.com/archethic-foundation/aeweb-cli/blob/main/commands/deploy_folder.js
5. https://github.com/archethic-foundation/aeweb-cli/blob/main/commands/deploy_website.js

This duplication can be reduced by analyzing the current codebase and implementing each execution separately.
Following are the functions which are duplicated and need to be separated -

- [x] Sending of transactions
- [x] File directory listing
- [x] Funds seeding for file based transaction
- [x] Content Allocation

**Comment by AmodD** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/aeweb-cli/39?planning-poker) with ZenHub @samuel-uniris @manujuniris
