### ISSUE TITLE
New test with AE Wallet

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/aeweb-cli#41]
### What happened?

Hello

- I pulled the project in local
- I copied in the project root my website (index.html + assets + folders) in a new /aeweb folder 
- i ran: ```aeweb generate-address --seed=aewallet --index=0  ```
- I put with Faucet 200 UCO to address 008762004834261ceb13d807e09b2907c97a19cdf45193afbf36f45851a335cd4d
- I ran ```aeweb deploy-website --seed=aewallet --endpoint=https://testnet.archethic.net --folder=aeweb```
I have nothing. no message in terminal

Could you help me please ?
Thx 

### What is expected ?

I expect a message to help me to understand what the program does
Thx

**Comment by redDwarf03** [comment]
[aeweb.zip](https://github.com/archethic-foundation/aeweb-cli/files/8124705/aeweb.zip)

Here's the folder

**Comment by manujuniris** [comment]
> ### What happened?
> Hello
> 
> * I pulled the project in local
> * I copied in the project root my website (index.html + assets + folders) in a new /aeweb folder
> * i ran: `aeweb generate-address --seed=aewallet --index=0  `
> * I put with Faucet 200 UCO to address 008762004834261ceb13d807e09b2907c97a19cdf45193afbf36f45851a335cd4d
> * I ran `aeweb deploy-website --seed=aewallet --endpoint=https://testnet.archethic.net --folder=aeweb`
>   I have nothing. no message in terminal
> 
> Could you help me please ? Thx
> 
> ### What is expected ?
> I expect a message to help me to understand what the program does Thx

I guess you missed sudo npm link, anyways very soon npm package will be updated. Hence, it will ease the process.

**Comment by redDwarf03** [comment]
Hello @manujuniris. Thank you for your answer 
ah ok. sudo npm link is no longer noted in readme.md I think
i retry with
```sudo npm link```

```npm install aeweb -g ```

```aeweb generate-address --seed=aewallet3 --index=0```
00e4ffa4f222016dd8b1d219d266ea058855f7adb19c0efb8d2bb775a4b7a1bf35
If you are using testnet go to https://testnet.archethic.net/faucet & add some funds to the generated address, otherwise transfer funds from your UCO wallet (in Mainnet)

I send 100 UCO to address with Faucet

```aeweb deploy-website --seed=aewallet3 --endpoint=https://testnet.archethic.net --folder=aeweb```

and no message

**Comment by redDwarf03** [comment]
for info, we have different tags in the index.html generated by flutter:
```
- <script src="splash/splash.js"></script>
- <source srcset="splash/img/light-1x.png 1x, splash/img/light-2x.png 2x, splash/img/light-3x.png 3x, splash/img/light-4x.png 4x" media="(prefers-color-scheme: light) or (prefers-color-scheme: no-preference)">
- scriptTag.src = 'main.dart.js?v=' + serviceWorkerVersion;
- var serviceWorkerUrl = 'flutter_service_worker.js?v=' + serviceWorkerVersion;
```

**Comment by samuel-uniris** [comment]
Is it still relevant @redDwarf03 ?

**Comment by redDwarf03** [comment]
deployment ok
