### ISSUE TITLE
Support nested html page analysis 

### ISSUE THREAD

**Issue by samuel-uniris** [archethic-foundation/aeweb-cli#43]
### Problem to solve

When we have a real static website you may be in a situation where some HTML page leads to other pages.So we should support nested HTML page analysis and transformation with transaction linking.

![nested_html](https://user-images.githubusercontent.com/90322956/160066506-b8665f7d-6aa6-47e1-b398-7efa0204fa7e.png)

Current Situation -
In the current situation, the CLI only works with index.html analysis.

### Solution

- [x] Fix transaction deployment
- [x] Target and traverse index.html 
- [x] Identify HTML files
- [X] Re-traverse HTML files
- [X] Replace the relevant files with transactions

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/aeweb-cli/43?planning-poker) with ZenHub @manujuniris @I-Archer-Zero @samuel-uniris

**Comment by prix-uniris** [comment]
Created a PR and requested @manujuniris  and @blackode for review. 
PR: #52 - Support nested html page analysis #43 #52
