### ISSUE TITLE
Inform the fee and wait approval

### ISSUE THREAD

**Issue by I-Archer-Zero** [archethic-foundation/aeweb-cli#44]
### Problem to solve

Whenever a user wants to deploy a transaction, the CLI should display the transaction fees along with the price of UCO in USD & EUR and at the same time, user confirmation must be taken such that he/she wants to proceed with the transaction deployment or not.

Current Situation - 
In the current situation, aeweb-cli displays only the transaction fees. 

![Screenshot from 2022-03-25 10-38-58](https://user-images.githubusercontent.com/90322956/160058334-702eca46-242b-4f88-91c6-bae7d6498092.png)

### Solution

- [x] Fetch the transaction fee (though the API) 
- [x] Display the price of UCO in USD & EUR 
- [x] After displaying the transaction fees, take user confirmation before deploying the transaction

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/aeweb-cli/44?planning-poker) with ZenHub @samuel-uniris @manujuniris @nilesh-uniris

**Comment by redDwarf03** [comment]
@I-Archer-Zero "add waitConfirmations" blocks the operation of the application. so I think you have to switch this issue into 2 issues because the priority is not the same between waitConfirmation and inform the transaction fee
