### ISSUE TITLE
Improve code quality with FP concepts

### ISSUE THREAD

**Issue by ghost** [archethic-foundation/aeweb-cli#56]
A first phase have been done, but we can improve it even more , to be more readable and maintainable. 

I suggest to leverage concepts from functional programming such as :
- data transformation (pure function)
- composition (chain of function calls)
- immutability

This will help to understand what the is doing , what are the expectation of function calls. 

Also this will make easy unit tests.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/aeweb-cli/56?planning-poker) with ZenHub @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris

**Comment by AmodD** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/aeweb-cli/56?planning-poker) with ZenHub @manujuniris
