### ISSUE TITLE
Automating images conversion to b64

### ISSUE THREAD

**Issue by manujuniris** [archethic-foundation/aeweb-cli#6]
When using HTML page as input, it will be good to convert into base64 the image, so the HTML page will hold the images inside the transaction.

However, we can propose a flag to skip the base64 conversion if we want so.

**Comment by I-Archer-Zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/aeweb-cli/6?planning-poker) with ZenHub @I-Archer-Zero @manujuniris @samuel-uniris
