### ISSUE TITLE
Handle complex website

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/aeweb-cli#60]
### Problem to solve

Actually, file's content is stored in a transaction and to access this content we need to request the api `api/last_transaction/ADDRESS/content`.
This means that if we want to upload multiple files which are linked (src in html file for example) we have to replace the name of the file by the api url.
There is many problem with this implementation : 
- We need to change the content of the file -> this can be complex and not always possible.
- Some file cannot have url in filepath, for example in javascript `import file from 'file.js'`, "file.js" cannot be replaced by url because import command do not handle it.
- If a website contains a lot of files (especially logo or png files) we have a lot of transaction and this can cost a lot

### Solution

When a web browser request an url, the server return the file which is located in the folder following the url path: 
"https://archethic.net/assets/css/style.css" will return the file located in assets/css which name is "style.css".

So the idea is to do the same behavior: everything after the endpoint is considered as folders and files.
To do it we can create a JSON text with the tree structure of the website folder with the file encoded in base64 or other format.
This JSON text is added in the content of a transaction and sent to the network.
For example assets/css/style.css will be 
```json
{
 "assets": {
  "css": {
   "style.css": {
    "encodage": "base64",
    "content": "BLABLABLA"
   }
  }
 }
}
```

Then to request the content of a specific file, we can create a new API "api/web_hosting/ADDRESS" and all path after the address is converted to a JSON path.
for exemple "https://endpoint/api/web_hosting/ADDRESS/assets/css/style.css" retrieve the content of the last transaction "ADDRESS" and then will retrieve in the content the JSON path assets -> css -> style.css then decode the content depending of the encodage method (base64, zip or other) and return the decoded content.

The advantage of this method is that we do not have to change the files and so every kind of file will works. We also have less transaction so less fees and it's easier to find the transaction according to our website.

What to do : 
- [x] Read the folder and create the JSON tree
- [x] Encode files content in base64 (other format will be added later)

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/aeweb-cli/60?planning-poker) with ZenHub @blackode @imnik11 @Neylix @roychowdhuryrohit-dev @samuel-uniris

**Comment by redDwarf03** [comment]
[Archethic_wallet_0.2.17.zip](https://github.com/archethic-foundation/aeweb-cli/files/8741897/Archethic_wallet_0.2.17.zip)
for your test
