### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toFixed')

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/aeweb-cli#65]
### What happened?

I tried to deploy Archethic Wallet on testnet
I had an issue (i clone the last version of project in local)

<img width="898" alt="Capture d’écran 2022-06-12 à 22 19 50" src="https://user-images.githubusercontent.com/68340133/173252117-2f28d330-9a9f-41c2-9d98-3fae6ae624f0.png">

### What is expected ?

no error :)

**Comment by samuel-uniris** [comment]
Fixed by dfe4eb566d00fc0e6f49319fa04c7894a49ab0bb
