### ISSUE TITLE
Error: connection: close

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/aeweb-cli#66]
### What happened?

i tried to host on testnet the wallet, but i met an issue
i did an error. i try to host a wrong folder ... i obtained an error but no explaination

![Capture d’écran 2022-06-12 à 22 23 06](https://user-images.githubusercontent.com/68340133/173252204-cf079487-24d4-4a0d-9c97-ea44f021d532.png)

### What is expected ?

Detail the error

**Comment by pvalette** [comment]
I have the same issue on testnet, works fine (push) for me for the local node

**Comment by samuel-uniris** [comment]
The current AEWeb master is not in sync with testnet but with master of archethic node yes.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/aeweb-cli/66?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris @samuel-uniris

**Comment by aime-risson** [comment]
Hello, has the AEWeb master been synced with the testnet yet ? I keep getting the error.
Thanks
