### ISSUE TITLE
Not possible to push a basic site

### ISSUE THREAD

**Issue by pvalette** [archethic-foundation/aeweb-cli#67]
### What happened?

With the latest version of the node (with the US for webhosting), able to push a web site but when I want to access the page, I have the error

**File index.html does not exist**

### What is expected ?

Display the website

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/aeweb-cli/67?planning-poker) with ZenHub @apoorv-2204 @imnik11 @Neylix @prix-uniris @samuel-uniris

**Comment by samuel-uniris** [comment]
This might be resolved in archethic-foundation/archethic-node#414

**Comment by samuel-uniris** [comment]
Otherwise, website resolving expect to find an index.html by default.
If it's not the case, you have to specify the file to display in the url

**Comment by samuelmanzanera** [comment]
Is this still relevant ?
