### ISSUE TITLE
Backward Support for older node.js version 

### ISSUE THREAD

**Issue by imnik11** [archethic-foundation/aeweb-cli#71]
### Describe the problem you discovered

when I try to deploy using older version on nodejs I faced the following error
![Screenshot 2022-07-11 223732](https://user-images.githubusercontent.com/45528152/178319505-842c8b14-02e0-482a-898a-237326883546.png)

### Describe the solution you'd like

Ideally it should support the older version of nodejs 
so, we need fix the base64url conversion for older versions

**Comment by samuelmanzanera** [comment]
We can create requirements in the package.json like this:
```json
 "engines": {
    "npm": ">=6.0.0",
    "node": ">=16.0.0"
  },
```

and create `.npmrc` file with: `engine-strict=true`
