### ISSUE TITLE
Reduce wait by parallelizing process 

### ISSUE THREAD

**Issue by imnik11** [archethic-foundation/aeweb-cli#72]
### Describe the problem you discovered

Creating transaction and estimating calculating fees taking large time in case of big files
![Screenshot 2022-07-11 231532](https://user-images.githubusercontent.com/45528152/178325716-1adaac5f-119e-4648-a449-6e3eecf01c2c.png)
 

### Describe the solution you'd like

so, we can perform this process concurrently and reduce the wait time.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/aeweb-cli/72?planning-poker) with Zenhub @samuelmanzanera @apoorv-2204 @Neylix
