### ISSUE TITLE
Amount management. Int format (10^8) from end to end

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/aeweb-cli#75]
### Describe the problem you discovered

Take charge of amount and fees format.
<img width="781" alt="Capture d’écran 2022-09-06 à 09 03 23" src="https://user-images.githubusercontent.com/68340133/188568419-2d544b2a-ed1f-4bad-8a96-eabfd0bc161d.png">

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/aeweb-cli/75?planning-poker) with Zenhub @samuelmanzanera @apoorv-2204 @Neylix

**Comment by samuelmanzanera** [comment]
This was impacted since https://github.com/archethic-foundation/archethic-node/pull/518.

We need to update libjs and transform big Int to readable int.
