### ISSUE TITLE
Update sending workflow with last libjs implementation

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/aeweb-cli#76]
### Is your feature request related to a problem?

New version of libjs changes the way to send transaction using a TransactionSender.

### Describe the solution you'd like

Adapt AEWeb to handle this new TransactionSender and display error if there is.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/aeweb-cli/76?planning-poker) with Zenhub @samuelmanzanera @Neylix @apoorv-2204
