### ISSUE TITLE
Support of .git folder and .gitignore

### ISSUE THREAD

**Issue by samuelmanzanera** [archethic-foundation/aeweb-cli#82]
### Is your feature request related to a problem?

If we are deploying in a folder containing .git, the CLI will deploy all the files including .git directory.

### Describe the solution you'd like

So to avoid unnecessary uploads, we should exclude .git folder and handle files/folder in .gitignore to avoid mistakes.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/aeweb-cli/82?planning-poker) with Zenhub @samuelmanzanera @Neylix @apoorv-2204

**Comment by Neylix** [comment]
Closed by #93
