### ISSUE TITLE
Handle website update

### ISSUE THREAD

**Issue by Neylix** [archethic-foundation/aeweb-cli#83]
### Is your feature request related to a problem?

Currently if we deploy a website and want to update it, all files are re deployed event if they are not updated.

### Describe the solution you'd like

If a website already exists, the CLI should get the hash of each files from the blockchain, compute the hash of new files and determine which files are updated or new.
The updated / new files are sent in the file chain.
We get the previous reference chain content, update only the updated / new files addresses and send the new reference chain content.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/aeweb-cli/83?planning-poker) with Zenhub @Neylix @samuelmanzanera @apoorv-2204
