### ISSUE TITLE
[bug][recurrent] Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by apoorv-2204** [archethic-foundation/aeweb-cli#99]
### Describe the problem you discovered

Though this issue was resolved, still its persistent, after changes from commit 4cf8c48746a4834e5dc40765c194c6bbc82b67dd
![image](https://user-images.githubusercontent.com/90304197/216054268-0e2e6380-0b64-4797-86ea-dd52a5e0f1fc.png)

### Describe the solution you'd like

make sure, .git and .gitignore are not uploaded

**Comment by samuelmanzanera** [comment]
If you remove the flag -i it should work

**Comment by apoorv-2204** [comment]
> If you remove the flag -i it should work

As per prev conversation, desgin proposed was .git to be removed by default
